### ISSUE TITLE
Gitlab link 404's

### ISSUE THREAD

**Issue by jnboehm** [emacscollective/emacs.g#1]
the supplied link in the readme [https://gitlab.com/emacscollective/emacs.g] is not found on Gitlab.  Maybe the repository isn't private.

**Comment by tarsius** [comment]
Indeed it was still set to private. Thanks!

**Comment by tarsius** [comment]
Are you still using `borg`? Please share your experience if you do.

**Comment by jnboehm** [comment]
Not now, I was planning on it but unfortunately never really got around 
to it.  It's still on my list, but customizing Emacs has stagnated in 
the last couple months.
