### ISSUE TITLE
`epkg` SHA in .gitmodules isn't present in repository

### ISSUE THREAD

**Issue by jcsims** [emacscollective/emacs.g#17]
The SHA `bc78f600b2c451bc8df1cf73bbb14476c11ece1d` that you updated to recently doesn't seem to be present in https://github.com/emacscollective/epkg. Do you have a local commit that didn't get pushed?

Also, thanks for all your work on borg and related packages, it's a really slick setup.

**Comment by tarsius** [comment]
Sorry about that. Pushed it now.
