### ISSUE TITLE
Clarify emacs.g License

### ISSUE THREAD

**Issue by cloudchin** [emacscollective/emacs.g#19]
I'm highly interested in using `emacs.g` to bootstrap Borg but have no idea what the implications are for using or distributing it given there is no provided license. 

Scenario:
My current personal configuration is a private repo that for embarrassing reasons I'd like to keep private. I want to combine that code with `Borg` and:

- Use it as a Git learning experience
- Use a more versatile Emacs configuration framework and avoid numerous package.el caveats
- Learn and better leverage git-related `magit`
- Follow provided instructions, using `emacs.g` as a bootstrap
- Keep my novice mess private, only opening later when it has achieved not-garbage status.
- When I 'inevitably' achieve legendary emacsen-status, have my then-public dotemacs not have any crazy licensing restrictions sprung on it or other crippling hindrances.

[You already provided instructions for creating a private repo, even explaining the "why" and "what" in git terms](https://github.com/emacscollective/emacs.g/issues/18) which is AWESOME, but you make no reference to Licensing and a lack of installation notes that would otherwise round out a well composed package kit seems... odd.

Related:
[How to Make a fork of public repository private?](https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private)
[How does GitHub's “forking right” cope with an “All rights reserved” project?](https://opensource.stackexchange.com/questions/1154/how-does-githubs-forking-right-cope-with-an-all-rights-reserved-project)

Full disclaimer:
I don't develop for a living, and I've never forked. Would love to be set straight.

**Comment by tarsius** [comment]
I would have preferred to leave this undefined but now you have forced my hand.

1. I believe that copyright does (or should not) apply to configuration.
2. I consider this repository to consist almost exclusively of configuration.

Only the seven line `Makefile` and four lines from from `init.el` are not configuration.  That's only eleven trivial lines, which also aren't (or should not be) copyrightable.

``` makefile
-include lib/borg/borg.mk

bootstrap-borg:
  	@git submodule--helper clone --name borg --path lib/borg \
	--url git@github.com:emacscollective/borg.git
	@cd lib/borg; git symbolic-ref HEAD refs/heads/master
	@cd lib/borg; git reset --hard HEAD

```

``` emacs-lisp
(progn ;    `borg'
  (add-to-list 'load-path (expand-file-name "lib/borg" user-emacs-directory))
  (require  'borg)
  (borg-initialize))
```

The rest boils down to many instances of "use package X" and "set variable Y to Z".  And a bit of documentation.

**Comment by cloudchin** [comment]
Thanks for clarifying, and for your emacs contributions.

I'm not sure how my question causes a "forced hand" though. Users need to know what the usability is for borrowed content. Leaving potential restrictions or complexities undocumented and undiscovered now can only hurt the noble efforts behind `emacscollective`. Do you disagree? Thinking it might help structure & disambiguate documentation too...

If you don't want sunlight on it (though that begs the question), maybe add a subtle link to your post in the readme?
