### ISSUE TITLE
How to use this starter to begin?

### ISSUE THREAD

**Issue by lld2001** [emacscollective/emacs.g#23]
I clone this repo and then run `make bootstrap-borg`, that only clone `borg` from github. All the other repos are still empty dir. So could you please help me, what's the next step to continue? I've tried `git submodule update --init --recursive` and also didn't work.

**Comment by lld2001** [comment]
Oh, it's because I download this repo from browser in github. That will miss `.git` dir.

**Comment by tarsius** [comment]
See https://emacsmirror.net/manual/borg/Bootstrapping-using-a-seed.html.

**Comment by lld2001** [comment]
I use `borg` in windows. After run `make bootstrap`,  there are many errors.

```shell
e:\emacs\.emacs.d>make bootstrap

=== Running 'git submodule init' ===


=== Running 'lib/borg/borg.sh' ===
lib/borg/borg.sh:行2: $'\r': 未找到命令 (Command not found)
lib/borg/borg.sh:行7: $'\r': 未找到命令  (Command not found)
lib/borg/borg.sh:行10: $'\r': 未找到命令 (Command not found)
lib/borg/borg.sh: 第 13 行:cd: $'e:/emacs/.emacs.d\r\r': No such file or directo
ry
lib/borg/borg.sh:行14: $'\r': 未找到命令(Command not found)
lib/borg/borg.sh:行15: $'\r': 未找到命令(Command not found)
lib/borg/borg.sh:行62: 未预期的符号 `elif' 附近有语法错误 (syntax error in `elif')
'ib/borg/borg.sh:行62: `                elif test "$remote" = "$push_remote"
make: *** [lib/borg/borg.mk:97：bootstrap] 错误 2
```

**Comment by lld2001** [comment]
What's the task of this script? Can I do it by hand?

**Comment by tarsius** [comment]
This file, like all other files, are checked in with unix line terminators (`\n`) into the repository. On your machine they appear to be checked out with dos/windows line terminators (`\r\n`), which makes sense since you are on windows. It appears though that your shell expects `\n`.

You can tell Git what file endings to check a file out with to work around this. See `core.eol` and subsequent variables in `man git-config`. It's probably best you search the web for articles about those variables. I don't have any experience with them and since this is not a Borg-specific issue I would appreciate it if you could get help for this elsewhere.

> What's the task of this script? Can I do it by hand using command or using elisp?

It clones all modules and compiles all elisp. You can use `git submodule update --init` instead, but that will forgo compilation. You can do that in a second step using `make build`.

You could also try to change the terminators once, using `dos2unix borg.sh`.

**Comment by lld2001** [comment]
> You can do that in a second step using `make build`.

This is what I want. Thank you for your patient answer!

I have used `git submodule update --init --recursive` to clone all modules before the previous error occured. Emacs can also start normaly after `git submodule update --init --recursive` . But I found `.el` files not automatic compiled. 

> [auto-compile doc](https://github.com/emacscollective/auto-compile#readme) says:
>> Starting with Emacs version 24.4, setting load-prefer-newer to t prevents outdated byte code files from being loaded. However this does not cause re-compilation of the source file, to actually do that auto-compile-on-load-mode is still required.

So I set `load-prefer-newer` to nil in early-init.el, but it still cannot auto-compile.

**Comment by lld2001** [comment]
There's a problem in below function 

```emacs-lisp
(defun borg--maybe-absorb-gitdir (pkg)
  (if nil;(version< (nth 2 (split-string (car (process-lines "git" "version")) " "))
           ;     "2.12.0")
      (let ((gitdir (borg-gitdir pkg))
            (topdir (borg-worktree pkg)))
        (unless (equal (let ((default-directory topdir))
                         (car (process-lines "git" "rev-parse" "--git-dir")))
                       (directory-file-name gitdir))
          (rename-file (expand-file-name ".git" topdir) gitdir)
          (borg--link-gitdir pkg)
          (let ((default-directory gitdir))
            (borg--call-git pkg "config" "core.worktree"
                            (concat "../../../lib/" pkg)))))
    (borg--call-git pkg "submodule" "absorbgitdirs" "--" (borg-worktree pkg))))
```

because git's version in windows is special (‘2.18.0.windows.1’):
version-to-list: Invalid version syntax: ‘2.18.0.windows.1’

So I comment that condition.

**Comment by tarsius** [comment]
I've pushed a fix for `borg--maybe-absorb-gitdir`.

**Comment by lld2001** [comment]
> make build, magit lib/<package-name> and M-x borg-build is how you should build packages.

`make` is not always available in Windows. So is it possible I substitute the make script by emacs operation or elisp?

**Comment by tarsius** [comment]
> `make` is not always available in Windows.

Let's say "it's complicated" instead. The "Windows Subsystem for Linux" stuff is probably the way forward. But I have no experience with that and don't use Windows, so I cannot help you there.

> So is it possible I substitute the make script by emacs operation or elisp?

Yes, the `Makefile` isn't that complicated. Well that is just a wrapper but `lib/borg/bork.mk` shouldn't be hard to translate. Not sure I would want to distribute this with `borg` (so far you seem to be the first person who wants to use this on a Windows that doesn't somehow has `make` available). But if you write such a script we could certainly add it to the wiki.

**Comment by lld2001** [comment]
I have to use Windows 7. So it's complicated. I have seek a method without dependent on `make`.

`make build` actually run the function `borg-batch-rebuild`. Could this function be modifed  to `Command`? I evaluate it, but it seems to use as a `batch scripte`.  So that I can run it in Emcas.

After these steps, I can start from this starter-kit without depent on `make` stuff. So maybe I can run `borg-batch-rebuild` within Emacs(all starter packages available, but can not auto-compile)

1. git clone https://github.com/emacscollective/emacs.g.git .emacs.d
2. change `.gitmodules` file. Modify all "git@"  to "https://" and  all "com:" to "com/". That use https instead of ssh
3. git submodule sync
4. git submodule update --init
5. then Emacs start normaly.

**Comment by lld2001** [comment]
I have migrated my conf to borg. Sorry to bother you. Thank you.

**Comment by tarsius** [comment]
Congratulations :grin:
