### ISSUE TITLE
Warnings on `make bootstrap`

### ISSUE THREAD

**Issue by sooheon** [emacscollective/emacs.g#3]
After cloning this repo to ~/.emacs.d, `make bootstrap` gives me the following errors at the end:

```
Error (use-package): eldoc :config: Symbol's function definition is void: global-eldoc-mode
Error (use-package): saveplace :config: Symbol's function definition is void: save-place-mode
Loading /Users/sooheon/.emacs.d/init.el...done (0.346s)
Compiling /Users/sooheon/.emacs.d/init.el...
Cannot load epkg: (file-error "Cannot open load file" "no such file or directory" "seq")

In end of data:
../../init.el:177:1:Warning: the function `magit-add-section-hook' might not
    be defined at runtime.
../../init.el:177:1:Warning: the following functions are not known to be
    defined: global-eldoc-mode, save-place-mode
Wrote /Users/sooheon/.emacs.d/init.elc
```

Is there some loading gone wrong? Using emacs 24.5.1

**Comment by sooheon** [comment]
Is the problem that these these two functions are only included in emacs 25?

**Comment by sooheon** [comment]
Yes it is :p.

**Comment by tarsius** [comment]
I will update the README to mention that currently the Emacs development version is required. I do plan to eventually always support at least the latest stable version, but decided to not complicate things for me while `borg` are still in the alpha-release period.
