### ISSUE TITLE
Subproject commit-foo-dirty

### ISSUE THREAD

**Issue by sooheon** [emacscollective/emacs.g#4]
In the magit status buffer of .emacs.d, I'm seeing these Unstaged changes of "dirty" commits which can never be staged. Is this normal? The more packages I assimilate, will I just have to deal with this clutter for every submodule?

<img width="692" alt="screen shot 2016-05-26 at 6 35 23 am" src="https://cloud.githubusercontent.com/assets/302945/15557129/4bea7d44-230c-11e6-8557-fefe3796c6b9.png">

**Comment by sooheon** [comment]
So this is because of git seeing the autoload.el and other files created by emacs. These are all uncommitted changes, so it sees them as dirty. It was only a matter of putting 
```
*-autoloads.el
*.elc
dir
```
into `.gitignore_global`

**Comment by tarsius** [comment]
He. I was just about to tell you that. Glad you figured it out ;-)

**Comment by sooheon** [comment]
Yep. have you had any problems with having `dir` a global gitignore? That's the one that bothers me. If I could, I'd rather prevent it from being made (it looks like something for info nodes?). Any experience there?

**Comment by tarsius** [comment]
> Yep. have you had any problems with having `dir` a global gitignore?

No, cannot think of any other files named `dir`.

> it looks like something for info nodes?

These files are needed by info. If they are not created, then info ignores the `*.info` files.
