### ISSUE TITLE
assimilating results in "Not a git repository" error

### ISSUE THREAD

**Issue by emacs18** [emacscollective/emacs.g#8]
On emacs 25 running on Ubuntu 16.04, I get "Not a git repository" when I tried to install a package.  Details follow.

I setup emacs.g via

```
$ git config --global url.https://github.com/.insteadOf git@github.com:
$ git config --global url.https://gitlab.com/.insteadOf git@gitlab.com:

$ git config --global core.excludesfile ~/.gitignore_global
$ echo '*-autoloads.el' >> ~/.gitignore_global
$ echo '*.elc' >> ~/.gitignore_global
$ echo 'dir' >> ~/.gitignore_global

$ cd ~/Private
$ git clone https://github.com/emacscollective/emacs.g emacs.g
$ cd emacs.g
$ make bootstrap
$ mkdir var
$ cd var
$ git clone https://github.com/emacsmirror/epkgs.git

$ rm -rf ~/.emacs.d
$ ln -s ~/Private/emacs.g ~/.emacs.d
```

then launched emacs 25 without any argument, and tried to install one package via

```
M-x borg-assimilate RET beacon RET
```

which resulted in this error message in the mini-buffer:

```
fatal: Not a git repository: ../../.git/modules/beacon
```

Despite the error message, it appears to me that at least the cloning process worked:

```
$ cd ~/Private/emacs.g
$ ls  .git/modules/beacon
branches  config  description  HEAD  hooks  index  info  logs  objects	packed-refs  refs
```

Did I missing something in my setup?
Should I just ignore this error message?

**Comment by tarsius** [comment]
What `git` release are you using?

**Comment by emacs18** [comment]
```
$ which git
/usr/bin/git
$ git --version
git version 2.7.4
$ 
```

**Comment by tarsius** [comment]
Could you please reopen this in the `borg` repository? I am much less likely to forget about this issue if it is being tracked there.
